import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './Providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Siddhesh Kukade',
  description: 'Generated by Siddhesh Kukade',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Providers>{children}</Providers></body>
    </html>
  )
}

// secret_fmBmClVvok3UJPbIcpGgvrw9sJwlw0cHLC3WGWmAhtU

//OAUTH CLient  ID c11d73dd-6e07-4354-8cb6-230a73826598
// OUTAH CLient secret secret_Qb7Ilhi5BOpCHSRUNa25RNrXCQzbPiPUxjDBQoOkmBd

//AUTH Url https://api.notion.com/v1/oauth/authorize?client_id=c11d73dd-6e07-4354-8cb6-230a73826598&response_type=code&owner=user&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F